version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: online_clothing_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://your_db_user:your_db_password@db:5432/online_clothing_store
      JWT_SECRET: your_jwt_secret
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
