-- Inserting data into the products table
INSERT INTO products (name, description, price, brand, category, size) VALUES
('Basic T-Shirt', 'Comfortable cotton t-shirt in various colors.', 15.99, 'BrandA', 'Apparel', 'M'),
('Denim Jeans', 'Classic denim jeans with a slim fit.', 39.99, 'BrandB', 'Apparel', 'L'),
('Leather Jacket', 'Stylish leather jacket for all seasons.', 149.99, 'BrandC', 'Apparel', 'M'),
('Running Shoes', 'High-performance running shoes for athletes.', 89.99, 'BrandD', 'Footwear', '9'),
('Casual Sneakers', 'Trendy sneakers for everyday wear.', 59.99, 'BrandE', 'Footwear', '8'),
('Wool Sweater', 'Warm wool sweater perfect for winter.', 89.99, 'BrandF', 'Apparel', 'L'),
('Summer Dress', 'Light and airy summer dress with floral patterns.', 29.99, 'BrandG', 'Apparel', 'S'),
('Winter Coat', 'Insulated winter coat with a hood.', 199.99, 'BrandH', 'Apparel', 'M'),
('Yoga Pants', 'Flexible yoga pants for comfort and style.', 29.99, 'BrandI', 'Apparel', 'L'),
('Sunglasses', 'UV-protection sunglasses with polarized lenses.', 24.99, 'BrandJ', 'Accessories', 'One Size'),
('Backpack', 'Durable backpack for everyday use.', 49.99, 'BrandK', 'Accessories', 'One Size'),
('Running Shorts', 'Breathable running shorts for optimal performance.', 24.99, 'BrandL', 'Apparel', 'M'),
('Watch', 'Elegant wristwatch with a leather band.', 119.99, 'BrandM', 'Accessories', 'One Size'),
('Laptop Bag', 'Protective laptop bag with padded compartments.', 69.99, 'BrandN', 'Accessories', 'One Size'),
('Baseball Cap', 'Adjustable baseball cap for sunny days.', 14.99, 'BrandO', 'Accessories', 'One Size'),
('Hoodie', 'Cozy hoodie with a front pocket.', 39.99, 'BrandP', 'Apparel', 'M'),
('Sneakers', 'Comfortable sneakers suitable for casual outings.', 69.99, 'BrandQ', 'Footwear', '10'),
('Scarf', 'Warm scarf made of premium wool.', 34.99, 'BrandR', 'Accessories', 'One Size'),
('Gloves', 'Thermal gloves for cold weather.', 19.99, 'BrandS', 'Accessories', 'One Size'),
('Formal Shirt', 'Elegant shirt for formal occasions.', 49.99, 'BrandT', 'Apparel', 'M'),
('Chinos', 'Casual chinos with a modern fit.', 34.99, 'BrandU', 'Apparel', 'L'),
('Winter Boots', 'Insulated winter boots for snowy conditions.', 129.99, 'BrandV', 'Footwear', '9'),
('Beach Towel', 'Quick-dry beach towel in vibrant colors.', 19.99, 'BrandW', 'Accessories', 'One Size'),
('Beanie', 'Soft knit beanie for cold weather.', 12.99, 'BrandX', 'Accessories', 'One Size'),
('Gym Bag', 'Spacious gym bag with multiple compartments.', 39.99, 'BrandY', 'Accessories', 'One Size'),
('Polo Shirt', 'Classic polo shirt with a tailored fit.', 29.99, 'BrandZ', 'Apparel', 'L'),
('Ski Jacket', 'Waterproof ski jacket with ventilation.', 229.99, 'BrandAA', 'Apparel', 'M'),
('Corduroy Pants', 'Stylish corduroy pants for a vintage look.', 49.99, 'BrandBB', 'Apparel', 'L'),
('Slippers', 'Comfortable indoor slippers with a soft sole.', 19.99, 'BrandCC', 'Footwear', '10'),
('Sundress', 'Flowy sundress for warm weather.', 34.99, 'BrandDD', 'Apparel', 'S'),
('Dress Shoes', 'Elegant dress shoes for formal events.', 89.99, 'BrandEE', 'Footwear', '8'),
('Trench Coat', 'Classic trench coat for rainy days.', 159.99, 'BrandFF', 'Apparel', 'M'),
('Cargo Shorts', 'Functional cargo shorts with multiple pockets.', 29.99, 'BrandGG', 'Apparel', 'M'),
('Belt', 'Leather belt with a stylish buckle.', 24.99, 'BrandHH', 'Accessories', 'One Size'),
('Umbrella', 'Compact umbrella for rainy days.', 14.99, 'BrandII', 'Accessories', 'One Size'),
('Tie', 'Silk tie with a modern pattern.', 22.99, 'BrandJJ', 'Accessories', 'One Size'),
('Hiking Boots', 'Durable hiking boots for outdoor adventures.', 119.99, 'BrandKK', 'Footwear', '11'),
('Sweater Vest', 'Warm sweater vest for layering.', 49.99, 'BrandLL', 'Apparel', 'L'),
('Cardigan', 'Soft cardigan with button closure.', 39.99, 'BrandMM', 'Apparel', 'M'),
('Wristband', 'Sporty wristband to absorb sweat.', 9.99, 'BrandNN', 'Accessories', 'One Size'),
('Footwear Cleaner', 'Special cleaner for keeping footwear in top condition.', 12.99, 'BrandOO', 'Accessories', 'One Size'),
('Raincoat', 'Lightweight raincoat for unexpected showers.', 49.99, 'BrandPP', 'Apparel', 'L'),
('Mittens', 'Warm mittens for extreme cold.', 15.99, 'BrandQQ', 'Accessories', 'One Size'),
('Fitness Tracker', 'Wearable fitness tracker for monitoring activity.', 79.99, 'BrandRR', 'Accessories', 'One Size'),
('Messenger Bag', 'Stylish messenger bag with adjustable strap.', 59.99, 'BrandSS', 'Accessories', 'One Size'),
('Workout Shorts', 'Comfortable workout shorts for exercise.', 24.99, 'BrandTT', 'Apparel', 'L'),
('Fanny Pack', 'Convenient fanny pack for carrying essentials.', 19.99, 'BrandUU', 'Accessories', 'One Size'),
('Face Mask', 'Reusable face mask for protection.', 9.99, 'BrandVV', 'Accessories', 'One Size'),
('Graphic T-Shirt', 'T-shirt with a unique graphic design.', 19.99, 'BrandWW', 'Apparel', 'M'),
('Leather Wallet', 'Compact leather wallet for daily use.', 29.99, 'BrandXX', 'Accessories', 'One Size');
